### ISSUE TITLE
Policy restricting Chrome history?

### ISSUE THREAD

**Issue by thw0rted** [nsacyber/Windows-Secure-Host-Baseline#62] opened 2018-09-08 11:13 UTC
I've got a machine based on the SHB, and the Chrome policy includes `URLBlacklist` as required in STIG `V-44761`, to disable `javascript://` URLs.  The issue is, it also blacklists `chrome://history` (so that the user cannot view their own browser history), but for the life of me I can't figure out where that additional value is coming from.  I can't find a STIG that requires this, and I can't find it in the policy sources here in the SHB repo.

Is there a STIG I'm missing that requires this?  Is it in the SHB?  If not, I can only assume it's a customization by the local org, and I'll have to run it down with our own IA, I guess.

**Comment by iadgovuser1** [comment] 2018-09-10 14:14
@thw0rted I think the latest GPOs provided by DISA have this setting value as a mistake. I sent a note to the SHB team a month or two ago to let them know about it. The GPOs in this repo are outdated so don't have that setting value.

**Comment by thw0rted** [comment] 2018-09-11 13:12
So, do you have a timeline for how long it might take for the average SHB-managed machine to correct this mistake?  I noticed this behavior ages ago but only recently thought to try to track down the STIG that motivated the policy.  This, along with a few other unevenly-enforced policy flags (no 3D APIs, no third-party cookies, etc) basically make Chrome the least useful browser on the SHB.

**Comment by iadgovuser1** [comment] 2018-09-11 22:48
Third-party cookies setting being disabled does break legitimate sites. That feedback was given a long time ago but that doesn't mean the feedback is acted upon. If the STIG is truly the source, then the feedback would need to be acted upon and incorporated in the next quarterly STIG update for Chrome. Whatever the next SHB release after that STIG update occurs is when it would be incorporated into the SHB framework download. However, applying the updated STIG could occur as soon as the quarterly update is released... if that setting change is made.

**Comment by thw0rted** [comment] 2018-09-12 07:24
I guess the frustrating part is that STIG guidance feels like the product of a faceless, monolithic bureaucracy and there's no feedback loop where damaging guidance can be corrected.  Obviously this tracker is not the place to get the STIG itself "fixed", but thanks for listening.

**Comment by Prowler2** [comment] 2018-09-25 02:36
Send an email to the below group box detailing your STIG issue.  Be sure you state the STIG name, version, V-ID where the issue is and any other pertinent details. I have used this method many times and usually get a response within 24 hours.  

Questions or comments?
Please contact DISA STIG Customer Support Desk: 
disa.stig_spt@mail.mil

**Comment by iadgovuser1** [comment] 2018-09-25 17:05
chrome://history isn't in the Chrome STIG (I checked R12 from July). I believe it was a mistake made by the SHB folks who make the actual GPOs that are posted on DISA's site. That's why I asked the SHB team to make the change rather than DISA.

**Comment by thw0rted** [comment] 2018-09-26 07:11
In case you're curious, I checked yesterday and our SHB'd machine no longer has the `chrome://history` blacklist.  Took a while, but your suggestion made it through -- thanks!

Also, Prowler, thanks for the tip and I might email them about the other policies that are biting me today.

**Comment by iadgovuser1** [comment] 2019-01-17 19:15
I think this was resolved so I'm closing this.

**Closed by iadgovuser1** 2019-01-17 19:15 UTC
Labels: question
